"""Seed sample real matrimonial user profiles into the users collection.

These are inserted into the `users` collection (with hashed passwords) so
Search and Recommendations have real DB-backed candidates to score.
"""
from datetime import datetime, timezone

# Kept for backward compat: legacy /profiles endpoint uses this
INITIAL_PROFILES = [
    {"id": "TJ1001", "profileFor": "Self", "gender": "Female", "name": "Priya Sharma", "age": 26,
     "religion": "Hindu", "community": "Brahmin", "education": "B.Tech & MBA from IIM Bangalore",
     "occupation": "Senior Product Manager", "state": "Maharashtra", "district": "Mumbai",
     "bio": "Passionate about classical dance, traveling, and tech innovation.",
     "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600",
     "mobile": "+91 98765 43210", "email": "priya.sharma@example.com", "verified": True},
    {"id": "TJ1002", "profileFor": "Self", "gender": "Male", "name": "Rohan Verma", "age": 29,
     "religion": "Hindu", "community": "Khatri", "education": "MS Computer Science, Stanford",
     "occupation": "Lead Software Architect", "state": "Karnataka", "district": "Bengaluru",
     "bio": "Avid reader, marathon runner, tech enthusiast.",
     "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600",
     "mobile": "+91 91234 56789", "email": "rohan.verma@example.com", "verified": True},
    {"id": "TJ1003", "profileFor": "Self", "gender": "Female", "name": "Ananya Iyer", "age": 25,
     "religion": "Hindu", "community": "Iyengar", "education": "MBBS, MD (Pediatrics)",
     "occupation": "Paediatric Resident Doctor", "state": "Tamil Nadu", "district": "Chennai",
     "bio": "Dedicated medical professional who loves Carnatic music and weekend trekking.",
     "photo": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600",
     "mobile": "+91 99887 76655", "email": "ananya.iyer@example.com", "verified": True},
    {"id": "TJ1004", "profileFor": "Self", "gender": "Male", "name": "Kabir Mehta", "age": 31,
     "religion": "Jain", "community": "Oswal", "education": "Chartered Accountant & CFA",
     "occupation": "Investment Banker", "state": "Maharashtra", "district": "Pune",
     "bio": "Calm, ambitious, and values-driven.",
     "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600",
     "mobile": "+91 97654 32109", "email": "kabir.mehta@example.com", "verified": True},
]

# Full-fledged users for the recommendation engine (inserted into `users`)
SAMPLE_USERS = [
    {
        "fullName": "Priya Sharma", "email": "priya.sharma@truejodi.com", "gender": "Female",
        "age": 26, "dob": "1999-05-14", "height": "5 ft 5 in", "maritalStatus": "Never Married",
        "religion": "Hindu", "community": "Brahmin", "motherTongue": "Hindi",
        "education": "MBA from IIM Bangalore", "occupation": "Senior Product Manager",
        "annualIncome": "20-30 LPA", "state": "Maharashtra", "district": "Mumbai",
        "mobile": "+91 98765 43210",
        "aboutMe": "Classical dancer, curious traveller, tech-savvy product leader who deeply values family bonds.",
        "familyDetails": "Nuclear family. Father — Retired IAS. Mother — Homemaker. One younger brother.",
        "partnerExpectations": "Educated, career-driven, kind, and rooted in Indian values.",
        "diet": "Vegetarian", "smoking": "No", "drinking": "No",
        "manglik": "Non-Manglik", "horoscope": "Available",
        "languages": ["Hindi", "English", "Marathi"], "hobbies": ["Dance", "Travel", "Reading"],
        "primary_photo_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800",
    },
    {
        "fullName": "Rohan Verma", "email": "rohan.verma@truejodi.com", "gender": "Male",
        "age": 29, "dob": "1996-02-20", "height": "5 ft 11 in", "maritalStatus": "Never Married",
        "religion": "Hindu", "community": "Khatri", "motherTongue": "Punjabi",
        "education": "MS Computer Science, Stanford", "occupation": "Lead Software Architect",
        "annualIncome": "50-75 LPA", "state": "Karnataka", "district": "Bengaluru",
        "mobile": "+91 91234 56789",
        "aboutMe": "Marathon runner, chess enthusiast, and tech leader building AI systems.",
        "familyDetails": "Joint family. Father — Businessman. Mother — Doctor. One elder sister (married).",
        "partnerExpectations": "Well-educated, independent, warm-hearted with strong family values.",
        "diet": "Non-Vegetarian", "smoking": "No", "drinking": "Occasionally",
        "manglik": "Non-Manglik", "languages": ["Punjabi", "Hindi", "English"],
        "hobbies": ["Running", "Chess", "Photography"],
        "primary_photo_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800",
    },
    {
        "fullName": "Ananya Iyer", "email": "ananya.iyer@truejodi.com", "gender": "Female",
        "age": 25, "dob": "2000-08-11", "height": "5 ft 4 in", "maritalStatus": "Never Married",
        "religion": "Hindu", "community": "Iyengar", "motherTongue": "Tamil",
        "education": "MBBS, MD (Pediatrics)", "occupation": "Paediatric Resident Doctor",
        "annualIncome": "10-15 LPA", "state": "Tamil Nadu", "district": "Chennai",
        "mobile": "+91 99887 76655",
        "aboutMe": "Compassionate paediatrician who loves Carnatic music and weekend treks.",
        "familyDetails": "Nuclear family. Father — Professor. Mother — Homemaker. One younger sister.",
        "partnerExpectations": "Kind-hearted, well-settled, family oriented partner.",
        "diet": "Vegetarian", "smoking": "No", "drinking": "No",
        "manglik": "Non-Manglik", "languages": ["Tamil", "English", "Hindi"],
        "hobbies": ["Carnatic Music", "Trekking", "Reading"],
        "primary_photo_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=800",
    },
    {
        "fullName": "Kabir Mehta", "email": "kabir.mehta@truejodi.com", "gender": "Male",
        "age": 31, "dob": "1994-03-05", "height": "6 ft 0 in", "maritalStatus": "Never Married",
        "religion": "Jain", "community": "Oswal", "motherTongue": "Gujarati",
        "education": "Chartered Accountant & CFA", "occupation": "Investment Banker",
        "annualIncome": "75-100 LPA", "state": "Maharashtra", "district": "Pune",
        "mobile": "+91 97654 32109",
        "aboutMe": "Calm, ambitious, values-driven. Passionate about culinary arts and badminton.",
        "familyDetails": "Business family based in Pune. Traditional yet progressive outlook.",
        "partnerExpectations": "Career-oriented, family-loving, culturally rooted.",
        "diet": "Vegetarian", "smoking": "No", "drinking": "No",
        "manglik": "Non-Manglik", "languages": ["Gujarati", "Hindi", "English"],
        "hobbies": ["Cooking", "Badminton", "Investing"],
        "primary_photo_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=800",
    },
    {
        "fullName": "Meera Nair", "email": "meera.nair@truejodi.com", "gender": "Female",
        "age": 27, "dob": "1998-11-02", "height": "5 ft 6 in", "maritalStatus": "Never Married",
        "religion": "Hindu", "community": "Nair", "motherTongue": "Malayalam",
        "education": "M.Tech, IIT Madras", "occupation": "Data Scientist",
        "annualIncome": "25-35 LPA", "state": "Karnataka", "district": "Bengaluru",
        "mobile": "+91 98450 12345",
        "aboutMe": "AI researcher who paints, treks, and volunteers on weekends.",
        "familyDetails": "Nuclear. Father — Bank Manager. Mother — Teacher. Only child.",
        "partnerExpectations": "Intellectually curious, honest, family-first person.",
        "diet": "Non-Vegetarian", "smoking": "No", "drinking": "No",
        "manglik": "Non-Manglik", "languages": ["Malayalam", "English", "Hindi"],
        "hobbies": ["Painting", "Trekking", "AI Research"],
        "primary_photo_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=800",
    },
    {
        "fullName": "Arjun Reddy", "email": "arjun.reddy@truejodi.com", "gender": "Male",
        "age": 30, "dob": "1995-06-18", "height": "5 ft 10 in", "maritalStatus": "Never Married",
        "religion": "Hindu", "community": "Reddy", "motherTongue": "Telugu",
        "education": "MBA, ISB Hyderabad", "occupation": "Startup Founder",
        "annualIncome": "40-50 LPA", "state": "Telangana", "district": "Hyderabad",
        "mobile": "+91 98765 11223",
        "aboutMe": "Entrepreneur building deep-tech products. Fitness enthusiast.",
        "familyDetails": "Business family. Traditional South Indian values.",
        "partnerExpectations": "Ambitious, kind, family-oriented.",
        "diet": "Non-Vegetarian", "smoking": "No", "drinking": "Occasionally",
        "manglik": "Manglik", "languages": ["Telugu", "English", "Hindi"],
        "hobbies": ["Fitness", "Startups", "Cricket"],
        "primary_photo_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=800",
    },
    {
        "fullName": "Sneha Kapoor", "email": "sneha.kapoor@truejodi.com", "gender": "Female",
        "age": 28, "dob": "1997-09-25", "height": "5 ft 5 in", "maritalStatus": "Never Married",
        "religion": "Hindu", "community": "Khatri", "motherTongue": "Punjabi",
        "education": "LLB from NLSIU", "occupation": "Corporate Lawyer",
        "annualIncome": "30-40 LPA", "state": "Delhi", "district": "New Delhi",
        "mobile": "+91 99101 22334",
        "aboutMe": "Corporate lawyer by day, salsa dancer by weekend. Foodie.",
        "familyDetails": "Nuclear family. Progressive values.",
        "partnerExpectations": "Independent, humorous, family-caring man.",
        "diet": "Non-Vegetarian", "smoking": "No", "drinking": "Occasionally",
        "manglik": "Non-Manglik", "languages": ["Punjabi", "English", "Hindi"],
        "hobbies": ["Salsa", "Food", "Travel"],
        "primary_photo_url": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=800",
    },
    {
        "fullName": "Vikram Singh", "email": "vikram.singh@truejodi.com", "gender": "Male",
        "age": 32, "dob": "1993-01-15", "height": "6 ft 1 in", "maritalStatus": "Never Married",
        "religion": "Sikh", "community": "Jat Sikh", "motherTongue": "Punjabi",
        "education": "B.Tech, IIT Delhi", "occupation": "Product Manager, FAANG",
        "annualIncome": "60-80 LPA", "state": "Haryana", "district": "Gurugram",
        "mobile": "+91 98110 44556",
        "aboutMe": "Tech PM who plays polo and rides Bullets. Traditional at heart.",
        "familyDetails": "Well-known Sikh family. Father — Retired Army Colonel.",
        "partnerExpectations": "Rooted, well-educated, kind partner.",
        "diet": "Non-Vegetarian", "smoking": "No", "drinking": "Occasionally",
        "languages": ["Punjabi", "English", "Hindi"],
        "hobbies": ["Polo", "Riding", "Startups"],
        "primary_photo_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=800",
    },
]
