from datetime import datetime, timezone

INITIAL_PROFILES = [
  {
    "id": "TJ1001",
    "profileFor": "Self",
    "gender": "Female",
    "name": "Priya Sharma",
    "age": 26,
    "religion": "Hindu",
    "community": "Brahmin",
    "education": "B.Tech & MBA from IIM Bangalore",
    "occupation": "Senior Product Manager",
    "state": "Maharashtra",
    "district": "Mumbai",
    "bio": "Passionate about classical dance, traveling, and tech innovation. Looking for an understanding partner with modern values and deep family roots.",
    "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600",
    "mobile": "+91 98765 43210",
    "email": "priya.sharma@example.com",
    "verified": True
  },
  {
    "id": "TJ1002",
    "profileFor": "Self",
    "gender": "Male",
    "name": "Rohan Verma",
    "age": 29,
    "religion": "Hindu",
    "community": "Khatri",
    "education": "MS in Computer Science, Stanford",
    "occupation": "Lead Software Architect",
    "state": "Karnataka",
    "district": "Bengaluru",
    "bio": "Avid reader, marathon runner, and tech enthusiast. Family-oriented with a balanced outlook on modern and traditional values.",
    "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600",
    "mobile": "+91 91234 56789",
    "email": "rohan.verma@example.com",
    "verified": True
  },
  {
    "id": "TJ1003",
    "profileFor": "Self",
    "gender": "Female",
    "name": "Ananya Iyer",
    "age": 25,
    "religion": "Hindu",
    "community": "Iyengar",
    "education": "MBBS, MD (Pediatrics)",
    "occupation": "Paediatric Resident Doctor",
    "state": "Tamil Nadu",
    "district": "Chennai",
    "bio": "Dedicated medical professional who loves Carnatic music and weekend trekking. Seeking a compassionate soul to share life's journey.",
    "photo": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600",
    "mobile": "+91 99887 76655",
    "email": "ananya.iyer@example.com",
    "verified": True
  },
  {
    "id": "TJ1004",
    "profileFor": "Self",
    "gender": "Male",
    "name": "Kabir Mehta",
    "age": 31,
    "religion": "Jain",
    "community": "Oswal",
    "education": "Chartered Accountant & CFA",
    "occupation": "Investment Banker",
    "state": "Maharashtra",
    "district": "Pune",
    "bio": "Calm, ambitious, and values-driven. Enjoys culinary arts, badminton, and spending time with loved ones.",
    "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600",
    "mobile": "+91 97654 32109",
    "email": "kabir.mehta@example.com",
    "verified": True
  }
]
